name: Docker CI Learning - KUCL 
on:
  push:
jobs:
  docker_1:
    runs-on: ubuntu-latest 
      #labels: kucl22 
         
    steps:
      -
        name: Set up QEMU test
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME}}/kucl22:actions
  deploy:
    needs: docker_1
    name: deploy image
    runs-on: ubuntu-latest

    steps:
      #      - name: install ssh keys
      # run: |
      #     install -m 600 -D /dev/null ~/.ssh/id_rsa
      #     echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
      #     ssh-keyscan -H ${{ secrets.D_HOST }} > ~/.ssh/known_hosts
      - name: connect and pull
        run: ssh ${{ secrets.S_USER }}@${{ secrets.D_HOST }} "cd ${{ secrets.WDIR }} && docker docker run -d ${{ secrets.DOCKERHUB_USERNAME}}/kucl22:actions  && exit"
      - name: cleanup
        run: rm -rf ~/.ssh
